import alertTest from './alert';
import avatarTest from './avatar';
import backtopTest from './back-top';
import badgeTest from './badge';
import breadcrumbTest from './breadcrumb';
import buttonTest from './button';
import cardTest from './card';
import collapseTest from './collapse';
import dividerTest from './divider';
import drawerTest from './drawer';
import dropdownTest from './dropdown';
// import inputNumberTest from './input-number';
import loadingBarTest from './loading-bar';
import messageTest from './message';
import poptipTest from './poptip';
import modalTest from './modal';
import noticeTest from './notice';
import progressTest from './progress';
import resultTest from './result';
import spinTest from './spin';
import stepsTest from './steps';
import switchTest from './switch';
import tabsTest from './tabs';
import tagTest from './tag';
import timeTest from './time';
import timelineTest from './timeline';
import tooltipTest from './tooltip';
import skeletonTest from './skeleton';

// alertTest();
// avatarTest();
// backtopTest();
// badgeTest();
// breadcrumbTest();
// buttonTest();
// cardTest();
// collapseTest();
// dividerTest();
// drawerTest();
// dropdownTest();
// inputNumberTest();
// loadingBarTest();
// messageTest();
// modalTest();
// noticeTest();
// poptipTest();
// progressTest();
// resultTest();
// skeletonTest();
// stepsTest();
// spinTest();
// switchTest();
// tabsTest();
// tagTest();
// timeTest();
// timelineTest();
// tooltipTest();
