import alertTest from './alert';
import avatarTest from './avatar';
import badgeTest from './badge';
import buttonTest from './button';
import cardTest from './card';
import dividerTest from './divider';
import loadingBarTest from './loading-bar';
import messageTest from './message';
import poptipTest from './poptip';
import noticeTest from './notice';
import progressTest from './progress';
import stepsTest from './steps';
import switchTest from './switch';
import timeTest from './time';
import timelineTest from './timeline';
import tooltipTest from './tooltip';

import '../src/styles/index.less';

// alertTest();
// avatarTest();
// progressTest();
// badgeTest();
// buttonTest();
// cardTest();
// dividerTest();
// loadingBarTest();
// messageTest();
// noticeTest();
// poptipTest();
// stepsTest();
// switchTest();
timeTest();
// timelineTest();
// tooltipTest();
