declare const _default: {
    alert: string;
    avatar: string;
    backtop: string;
    badge: string;
    button: string;
    card: string;
    collapse: string;
    divider: string;
    drawer: string;
    dropdown: string;
    icon: string;
    loadingBar: string;
    message: string;
    messageChild: string;
    modal: string;
    notice: string;
    poptip: string;
    noticeChild: string;
    progress: string;
    switch: string;
    tabs: string;
    spin: string;
    steps: string;
    time: string;
    timeline: string;
    tooltip: string;
};
export default _default;
