const prefixCls = 'rab-';

export default {
    alert: `${prefixCls}alert`,
    avatar: `${prefixCls}avatar`,
    backtop: `${prefixCls}back-top`,
    badge: `${prefixCls}badge`,
    button: `${prefixCls}btn`,
    card: `${prefixCls}card`,
    carousel: `${prefixCls}carousel`,
    collapse: `${prefixCls}collapse`,
    divider: `${prefixCls}divider`,
    drawer: `${prefixCls}drawer`,
    dropdown: `${prefixCls}dropdown`,
    icon: `${prefixCls}icon`,
    loadingBar: `${prefixCls}loading-bar`,
    message: `${prefixCls}message`,
    messageChild: `${prefixCls}message-notice`,
    modal: `${prefixCls}modal`,
    notice: `${prefixCls}notice`,
    poptip: `${prefixCls}poptip`,
    noticeChild: `${prefixCls}notice-notice`,
    progress: `${prefixCls}progress`,
    result: `${prefixCls}result`,
    skeleton: `${prefixCls}skeleton`,
    switch: `${prefixCls}switch`,
    tabs: `${prefixCls}tabs`,
    tag: `${prefixCls}tag`,
    spin: `${prefixCls}spin`,
    steps: `${prefixCls}steps`,
    time: `${prefixCls}time`,
    timeline: `${prefixCls}timeline`,
    tooltip: `${prefixCls}tooltip`
};
